FROM node:22.12.0-alpine3.20 AS common
WORKDIR /app

FROM common AS build

RUN apt-get update && apt-get install -y \
  build-essential \
  python3

COPY ./ /app

RUN npm install -g pnpm@10.6.4
RUN pnpm install --filter=@airstate/server...
RUN pnpm turbo run build --filter=@airstate/server...
RUN pnpm --filter=@airstate/server --prod deploy /airstate-server

FROM common AS production

COPY --from=build /airstate-server .

CMD node .
