FROM node:22.6.0-alpine3.20 AS common
WORKDIR /app

FROM common AS build
COPY . /app
RUN npm install -g pnpm@9.12.0
RUN pnpm install
RUN pnpm turbo run build --filter=@airstate/server
RUN pnpm --filter=@airstate/server --prod deploy /airstate-server

FROM common

ENV NODE_ENV=production
COPY --from=build /airstate-server .

CMD node .