FROM node:22.12.0-bookworm AS build

WORKDIR /app

RUN apt-get update && apt-get install -y \
  build-essential \
  python3

COPY . .

RUN npm install -g pnpm@9.12.0
RUN pnpm install
RUN pnpm turbo run build --filter=@airstate/server
RUN pnpm --filter=@airstate/server --prod deploy /airstate-server

FROM node:22.6.0-alpine3.20 AS production

WORKDIR /app

COPY --from=build /airstate-server .

EXPOSE 11001

CMD ["node", "."]