name: airstate
services:
    mono:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /mono
        command: pnpm run dev
        environment:
            NODE_ENV: development
            AIRSTATE_NATS_URL: 'nats://nats:4222'
            AIRSTATE_PORT: 11001
            AIRSTATE_VALKEY_URL: 'redis://valkey:6379'

        ports:
            - target: 11001 # `server` HTTP port
              published: 11001
              protocol: tcp

            - target: 15001 # `server` HTTP port
              published: 15001
              protocol: tcp

            - target: 11002 # `examples` HTTP port
              published: 11002
              protocol: tcp

            - target: 11003 # `go-server-tester` HTTP port
              published: 11003
              protocol: tcp

        volumes:
            - source: .
              target: /mono
              type: bind

            - source: mono-pnpm-store
              target: /mono/.pnpm-store
              type: volume

        depends_on:
            - valkey
            - nats

    valkey:
        restart: unless-stopped
        image: bitnami/valkey:8.1.1
        environment:
            ALLOW_EMPTY_PASSWORD: yes
        ports:
            - target: 6379
              published: 6380 # changed; in case you have a local redis running
              protocol: tcp
        volumes:
            - target: /bitnami/valkey/data
              source: valkey-data
              type: volume

    nats:
        restart: unless-stopped
        image: nats:2.11.1-alpine3.21

        ports:
            # client connections
            - published: 4222
              target: 4222
              protocol: tcp

            # monitoring UI
            - published: 8222
              target: 8222
              protocol: tcp

        volumes:
            - source: ./apps/server/nats-server.conf
              target: /etc/nats/nats-server.conf
              type: bind

            - target: /data
              source: nats-storage
              type: volume

        command: [ "-c", "/etc/nats/nats-server.conf", "--server_name", "nats" ]

volumes:
    # named volumes; they aren't removed on `docker compose down`
    mono-pnpm-store:
    valkey-data:
    nats-storage:
