FROM golang:1.25-bookworm

RUN apt update
RUN apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
RUN apt install -y nodejs
RUN npm install -g pnpm

RUN echo 'export PATH=/usr/local/go/bin:$PATH' >> /etc/profile
