name: Deploy Nats to Railway

on:
    push:
        branches:
            - production-server
        paths:
            - 'infra/nats/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Railway CLI
              run: |
                  curl -fsSL https://railway.app/install.sh | sh
                  echo "$HOME/.railway/bin" >> $GITHUB_PATH

            - name: Deploy Nats to Railway
              run: |
                  cd infra/Nats
                  railway up --service nats --verbose
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}
