name: Build and Publish Server to Docker Hub

on:
  push:
    branches: [main]
    paths:
      - 'apps/server/**'
      - '.github/workflows/publish-server-to-dockerhub.yml'
      - 'apps/server/Dockerfile'

  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: airstate/server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: apps/server
        run: |
          docker build \
            -t airstate/server:${{ github.sha }} \
            -t airsatte/server:dev-latest \
            -f Dockerfile .
          
          docker push airstate/server:${{ github.sha }}
          docker push airstate/server:dev-latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: The office AirState Server image
          readme-filepath: ./apps/server/README.md
