name: Publish `@airstate/client` to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
      - '.github/workflows/publish-vanilla-client-to-npm.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Check for new version
        uses: salsify/action-detect-and-tag-new-version@v2
        id: detect-new-version
        with:
          create-tag: false
          version-command: |
            jq -r '.version' packages/client/package.json

      - name: Publish to NPM
        if: steps.detect-new-version.outputs.previous-version != steps.detect-new-version.outputs.current-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing to NPM..."
          sudo npm install -g pnpm
          
          pnpm install 
          
          # Read version from package.json and store in a variable
          VERSION=$(jq -r '.version' packages/client/package.json)
          echo "Package version: $VERSION"
          
          # Replace "dev" with the version in src/version.mts
          echo "Updating version in src/version.mts ..."
          sed -i "s/dev/$VERSION/g" packages/client/src/version.mts
          cat packages/client/src/version.mts

          pnpm run build --filter=@airstate/client...
          
          cd packages/client
          pnpm publish --access public --no-git-checks