name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - 0.x

jobs:
  release:
    name: Publish Packages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Install Deps
        run: |
          pnpm install --frozen-lockfile \
            --filter=@airstate/mono \
            --filter=@airstate/client... \
            --filter=@airstate/react...
        env:
          SKIP_IP_DB_UPDATE: true

      - name: Build
        run: |
          pnpm turbo run build \
            --filter=@airstate/client... \
            --filter=@airstate/react...

      - uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
