name: Update the dockerhub description for airstate/server

on:
    push:
        tags:
          - '[0-9]+.[0-9]+.[0-9]+'

    release:
        types: [published]

env:
    IMAGE_NAME: airstate/server

jobs:
    update-hub-description:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v4
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                  repository: ${{ env.IMAGE_NAME }}
                  short-description: The office AirState Server image
                  readme-filepath: ./apps/server/README.md
