name: V2 Server to Railway

on:
  push:
    branches:
      - v2-server

    paths:
      - apps/server-rapid/**/*
      - .github/workflows/v2-server-to-railway.yml
      - Dockerfile_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install
        run: |
          npm install -g pnpm

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Rename to use `railway_server.json`
        run: cp railway_server.json railway.json

      - name: Deploy
        run: |
          railway up --service v2-server --verbose
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}