name: Create Version PR

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - 0.x
    paths:
      - .changeset/**/*.md
jobs:
  version:
    name: Versioning PR
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Install Deps
        run: pnpm install --frozen-lockfile --filter=@airstate/mono
      - uses: changesets/action@v1
        with:
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git tag
      - run: git branch
